import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

/**
 * A layout file/component is reserved by NextJS to be used as a wrapper of the application
 * It needs at leas one of this kind to render the application (at root level)
 */

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

/**
 * The metadata object is a reserved name that once exported, it will set several
 * metadata fields that will be used on the specific layout (it like using a <head> tag)
 */
export const metadata: Metadata = {
  title: 'Exercise #2 | Next Essentials Concepts',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
